### ISSUE TITLE
Long HTML input (>25.000 characters) is cut off

### ISSUE THREAD

**Issue by cowera** [tgalopin/html-sanitizer#56] opened 2021-01-05 18:53 UTC

**Comment by tgalopin** [comment] 2021-01-05 22:24
Yes, you can configure it: https://github.com/tgalopin/html-sanitizer/blob/master/src/Sanitizer.php#L80 (key `max_input_length` in the config array if you use the builder: https://github.com/tgalopin/html-sanitizer/blob/master/src/SanitizerBuilder.php#L108)

**Comment by kadet1090** [comment] 2021-02-27 18:35
I don't really think that default 20,000 characters is really sufficient - and this is really strange bug to search for. I understand that this is intended behavior and this limit limit makes sense, but it certainly should be much bigger, maybe 1mb of text? Or 200kb at least?

**Comment by tgalopin** [comment] 2021-02-27 19:32
20k characters is usually enough for most use cases where users input content, but I do understand it may not be enough for CMS usages for instance. Increasing it would leave the site open to DOS attacks though, as the parsing is CPU intensive and posting a lot of content on it could make the server unavailable. I'm not sure there is an ideal solution here :/ .

**Comment by kadet1090** [comment] 2021-02-28 12:55
Well it may be enough for comments - but not for page content. I understand that this is serious DoS possibility - but there are few things that should be taken into account, at least in my opinion.

First of all HTML sanitization should be done once and then the result should somehow be cached, minimizing the attack opportunities. Also, what is the source of 20k value, is it just some arbitrary "good enough" value? If it is just arbitrary - maybe it should be picked by some benchmarks? Let's say we don't want sanitization to took longer than 50ms, then we have to find some "nice" value that will be as close as possible to 50ms on some hardware (maybe digitalocean droplet? or some other representative hosting provider)

Secondly, if the default limit will be increased the problem will still occur. Personally I think that this should be visibly noted in documentation, and for the symfony bundle it should be copied to `.yml` configuration so it would be visible to everyone. 

And finally - this truncation should not be done silently. Maybe emit some kind of notice or warning so developers could find what is going on? It'd also be useful to know if someone is trying to dos us.

**Comment by tgalopin** [comment] 2021-02-28 13:04
I don't mind changing this default, I just don't see a better solution right now. 

Initially, the value was chosen to after working on html5-php (the parser used internally) and based on benchmarks, yes.

I am definitely in favor of highlight it more in the README and in the default config, +1. Feel free to open a PR!

**Closed as completed** 2021-12-15 14:23 UTC
